/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProposalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commitVote"
      | "commitments"
      | "confidentialProtocolId"
      | "dao"
      | "decryptResult"
      | "description"
      | "execute"
      | "executionData"
      | "getEncryptedVotes"
      | "getProposalInfo"
      | "getProposalStatus"
      | "info"
      | "revealVote"
      | "revealed"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProposalExecuted"
      | "PublicDecryptionVerified"
      | "VoteCommitted"
      | "VoteRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commitVote",
    values: [BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dao", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decryptResult",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "execute", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executionData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalStatus",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "info", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revealVote",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealed",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "commitVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dao", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decryptResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executionData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "info", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revealVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revealed", data: BytesLike): Result;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDecryptionVerifiedEvent {
  export type InputTuple = [
    handlesList: BytesLike[],
    abiEncodedCleartexts: BytesLike
  ];
  export type OutputTuple = [
    handlesList: string[],
    abiEncodedCleartexts: string
  ];
  export interface OutputObject {
    handlesList: string[];
    abiEncodedCleartexts: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCommittedEvent {
  export type InputTuple = [committer: AddressLike, commitment: BytesLike];
  export type OutputTuple = [committer: string, commitment: string];
  export interface OutputObject {
    committer: string;
    commitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteRevealedEvent {
  export type InputTuple = [revealer: AddressLike];
  export type OutputTuple = [revealer: string];
  export interface OutputObject {
    revealer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Proposal extends BaseContract {
  connect(runner?: ContractRunner | null): Proposal;
  waitForDeployment(): Promise<this>;

  interface: ProposalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commitVote: TypedContractMethod<
    [proof: BytesLike[], commitment: BytesLike],
    [void],
    "nonpayable"
  >;

  commitments: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  dao: TypedContractMethod<[], [string], "view">;

  decryptResult: TypedContractMethod<
    [abiEncodedResult: BytesLike, decryptionProof: BytesLike],
    [void],
    "nonpayable"
  >;

  description: TypedContractMethod<[], [string], "view">;

  execute: TypedContractMethod<[], [void], "nonpayable">;

  executionData: TypedContractMethod<
    [],
    [
      [string, bigint, string] & {
        targetAddress: string;
        value: bigint;
        executionCalldata: string;
      }
    ],
    "view"
  >;

  getEncryptedVotes: TypedContractMethod<[], [[string, string]], "view">;

  getProposalInfo: TypedContractMethod<
    [],
    [
      [bigint, string, bigint, bigint, string, bigint, string] & {
        _proposalId: bigint;
        _description: string;
        _commitEnd: bigint;
        _revealEnd: bigint;
        _target: string;
        _value: bigint;
        _calldata: string;
      }
    ],
    "view"
  >;

  getProposalStatus: TypedContractMethod<
    [],
    [
      [boolean, boolean, boolean, boolean, boolean, boolean] & {
        _canCommit: boolean;
        _canReveal: boolean;
        _executed: boolean;
        _decrypted: boolean;
        _isActived: boolean;
        _isApproved: boolean;
      }
    ],
    "view"
  >;

  info: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, boolean, bigint, bigint] & {
        proposalId: bigint;
        commitEnd: bigint;
        revealEnd: bigint;
        executed: boolean;
        decrypted: boolean;
        decryptedYesVotes: bigint;
        decryptedNoVotes: bigint;
      }
    ],
    "view"
  >;

  revealVote: TypedContractMethod<
    [esupport: BytesLike, salt: BytesLike, attestation: BytesLike],
    [void],
    "nonpayable"
  >;

  revealed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commitVote"
  ): TypedContractMethod<
    [proof: BytesLike[], commitment: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dao"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decryptResult"
  ): TypedContractMethod<
    [abiEncodedResult: BytesLike, decryptionProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "description"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executionData"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, string] & {
        targetAddress: string;
        value: bigint;
        executionCalldata: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedVotes"
  ): TypedContractMethod<[], [[string, string]], "view">;
  getFunction(
    nameOrSignature: "getProposalInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, string, bigint, bigint, string, bigint, string] & {
        _proposalId: bigint;
        _description: string;
        _commitEnd: bigint;
        _revealEnd: bigint;
        _target: string;
        _value: bigint;
        _calldata: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, boolean, boolean, boolean, boolean, boolean] & {
        _canCommit: boolean;
        _canReveal: boolean;
        _executed: boolean;
        _decrypted: boolean;
        _isActived: boolean;
        _isApproved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "info"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, boolean, bigint, bigint] & {
        proposalId: bigint;
        commitEnd: bigint;
        revealEnd: bigint;
        executed: boolean;
        decrypted: boolean;
        decryptedYesVotes: bigint;
        decryptedNoVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revealVote"
  ): TypedContractMethod<
    [esupport: BytesLike, salt: BytesLike, attestation: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revealed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PublicDecryptionVerified"
  ): TypedContractEvent<
    PublicDecryptionVerifiedEvent.InputTuple,
    PublicDecryptionVerifiedEvent.OutputTuple,
    PublicDecryptionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCommitted"
  ): TypedContractEvent<
    VoteCommittedEvent.InputTuple,
    VoteCommittedEvent.OutputTuple,
    VoteCommittedEvent.OutputObject
  >;
  getEvent(
    key: "VoteRevealed"
  ): TypedContractEvent<
    VoteRevealedEvent.InputTuple,
    VoteRevealedEvent.OutputTuple,
    VoteRevealedEvent.OutputObject
  >;

  filters: {
    "ProposalExecuted(address)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "PublicDecryptionVerified(bytes32[],bytes)": TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
    PublicDecryptionVerified: TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;

    "VoteCommitted(address,bytes32)": TypedContractEvent<
      VoteCommittedEvent.InputTuple,
      VoteCommittedEvent.OutputTuple,
      VoteCommittedEvent.OutputObject
    >;
    VoteCommitted: TypedContractEvent<
      VoteCommittedEvent.InputTuple,
      VoteCommittedEvent.OutputTuple,
      VoteCommittedEvent.OutputObject
    >;

    "VoteRevealed(address)": TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
    VoteRevealed: TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
  };
}
